# Generated by Django 4.0.5 on 2022-06-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tier",
            name="thumbnail_height",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
