# Generated by Django 4.0.5 on 2022-06-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_rename_live_seconds_expiringimage_live_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
