# Generated by Django 4.0.5 on 2022-06-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_rename_date_added_image_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='expiration_time',
        ),
    ]
